## Data Analysis

## Date : 4/09/2025

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: C:\Users\user\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

# Functions
## Function Def

In [5]:
def student_info(name, age = 18):
    print(name, age)

## Function Calling

In [8]:
student_info("Alice")

Alice 18


In [3]:
def fun():
    print("Welcome to GFG")
    
fun() # Driver code to call a function

Welcome to GFG


In [4]:
def evenOdd(x):
    if (x % 2 == 0):
        return "Even"
    else:
        return "Odd"

print(evenOdd(16))
print(evenOdd(7))

Even
Odd


In [9]:
def calculator(a, b):
    sum = a + b
    substract = a - b
    multiply = a * b
    divide = a / b
    return sum, substract, multiply, divide


print(calculator(20, 10))

(30, 10, 200, 2.0)


In [12]:
import math 
from math import sqrt
import math as m

In [14]:
math.sqrt(16)
m.sqrt(25)


5.0

### NUMPY

In [ ]:
## IMPORTING NUMPY
import numpy as np
a = np.array([1, 2, 3])
print(a) 

[1 2 3]


In [20]:
b = np.array([[1,2,3],
              [4,5,6,]])
print(b)

[[1 2 3]
 [4 5 6]]


In [23]:
c = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(c)    

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Pandas

In [25]:
!pip install pandas
import pandas as pd


[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: C:\Users\user\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [27]:
s = pd.Series([1, 3, 5, 7, 9])
print(s)
type(s)

0    1
1    3
2    5
3    7
4    9
dtype: int64


pandas.core.series.Series

In [28]:
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 28],
        'City': ['New York', 'London', 'Paris', 'New York'],
        'Salary': [70000, 80000, 90000, 75000]}
df = pd.DataFrame(data)
print(df)
type(df)

      Name  Age      City  Salary
0    Alice   25  New York   70000
1      Bob   30    London   80000
2  Charlie   35     Paris   90000
3    David   28  New York   75000


pandas.core.frame.DataFrame

In [29]:
df = pd.read_csv('new_data.csv')

In [30]:
df.head()

Date      Time    Booking ID   Booking Status   Customer ID  \
0  23-03-2024  12:29:38  "CNR5884300"  No Driver Found  "CID1982111"   
1  29-11-2024  18:01:39  "CNR1326809"       Incomplete  "CID4604802"   
2  23-08-2024  08:56:10  "CNR8494506"        Completed  "CID9202816"   
3  21-10-2024  17:17:25  "CNR8906825"        Completed  "CID2610914"   
4  16-09-2024  22:08:00  "CNR1950162"        Completed  "CID9933542"   

    Vehicle Type      Pickup Location      Drop Location  Avg VTAT  Avg CTAT  \
0          eBike          Palam Vihar            Jhilmil       NaN       NaN   
1       Go Sedan        Shastri Nagar  Gurgaon Sector 56       4.9      14.0   
2           Auto              Khandsa      Malviya Nagar      13.4      25.8   
3  Premier Sedan  Central Secretariat           Inderlok      13.1      28.5   
4           Bike     Ghitorni Village        Khan Market       5.3      19.6   

   ...  Reason for cancelling by Customer Cancelled Rides by Driver  \
0  ...                                NaN                       NaN   
1  ...                                NaN                       NaN   
2  ...                                NaN                       NaN   
3  ...                                NaN                       NaN   
4  ...                                NaN                       NaN   

   Driver Cancellation Reason Incomplete Rides  Incomplete Rides Reason  \
0                         NaN              NaN                      NaN   
1                         NaN              1.0        Vehicle Breakdown   
2                         NaN              NaN                      NaN   
3                         NaN              NaN                      NaN   
4                         NaN              NaN                      NaN   

  Booking Value  Ride Distance  Driver Ratings  Customer Rating  \
0           NaN            NaN             NaN              NaN   
1         237.0           5.73             NaN              NaN   
2         627.0          13.58             4.9              4.9   
3         416.0          34.02             4.6              5.0   
4         737.0          48.21             4.1              4.3   

   Payment Method  
0             NaN  
1             UPI  
2      Debit Card  
3             UPI  
4             UPI  

[5 rows x 21 columns]

In [31]:
df.tail()

Date      Time    Booking ID Booking Status   Customer ID  \
149995  11-11-2024  19:34:01  "CNR6500631"      Completed  "CID4337371"   
149996  24-11-2024  15:55:09  "CNR2468611"      Completed  "CID2325623"   
149997  18-09-2024  10:55:15  "CNR6358306"      Completed  "CID9925486"   
149998  05-10-2024  07:53:34  "CNR3030099"      Completed  "CID9415487"   
149999  10-03-2024  15:38:03  "CNR3447390"      Completed  "CID4108667"   

         Vehicle Type         Pickup Location      Drop Location  Avg VTAT  \
149995        Go Mini                 MG Road           Ghitorni      10.2   
149996        Go Mini        Golf Course Road         Akshardham       5.1   
149997       Go Sedan  Satguru Ram Singh Marg           Jor Bagh       2.7   
149998           Auto               Ghaziabad         Saidulajab       6.9   
149999  Premier Sedan         Ashok Park Main  Gurgaon Sector 29       3.5   

        Avg CTAT  ...  Reason for cancelling by Customer  \
149995      44.4  ...                                NaN   
149996      30.8  ...                                NaN   
149997      23.4  ...                                NaN   
149998      39.6  ...                                NaN   
149999      33.7  ...                                NaN   

       Cancelled Rides by Driver  Driver Cancellation Reason Incomplete Rides  \
149995                       NaN                         NaN              NaN   
149996                       NaN                         NaN              NaN   
149997                       NaN                         NaN              NaN   
149998                       NaN                         NaN              NaN   
149999                       NaN                         NaN              NaN   

        Incomplete Rides Reason Booking Value  Ride Distance  Driver Ratings  \
149995                      NaN         475.0          40.08             3.7   
149996                      NaN        1093.0          21.31             4.8   
149997                      NaN         852.0          15.93             3.9   
149998                      NaN         333.0          45.54             4.1   
149999                      NaN         806.0          21.19             4.6   

        Customer Rating  Payment Method  
149995              4.1     Uber Wallet  
149996              5.0             UPI  
149997              4.4            Cash  
149998              3.7             UPI  
149999              4.9     Credit Card  

[5 rows x 21 columns]

In [33]:
! pip install kagglehub

     ---------------------------------------- 0.0/57.7 kB ? eta -:--:--
     ---------------------------------------- 57.7/57.7 kB 1.5 MB/s eta 0:00:00
   ---------------------------------------- 0.0/68.3 kB ? eta -:--:--
   ---------------------------------------- 68.3/68.3 kB 3.6 MB/s eta 0:00:00
   ---------------------------------------- 0.0/162.0 kB ? eta -:--:--
   ------------------------------------- -- 153.6/162.0 kB 9.6 MB/s eta 0:00:01
   ---------------------------------------- 162.0/162.0 kB 4.9 MB/s eta 0:00:00
   ---------------------------------------- 0.0/64.7 kB ? eta -:--:--
   ---------------------------------------- 64.7/64.7 kB 3.4 MB/s eta 0:00:00
   ---------------------------------------- 0.0/78.5 kB ? eta -:--:--
   ---------------------------------------- 78.5/78.5 kB 4.6 MB/s eta 0:00:00
   ---------------------------------------- 0.0/161.2 kB ? eta -:--:--
   --------------------------------------- 161.2/161.2 kB 10.1 MB/s eta 0:00:00
   -------------------


[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: C:\Users\user\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [34]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("yashdevladdha/uber-ride-analytics-dashboard")

print("Path to dataset files:", path)

C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


100%|██████████| 16.5M/16.5M [00:02<00:00, 6.05MB/s]

Extracting files...


Path to dataset files: C:\Users\user\.cache\kagglehub\datasets\yashdevladdha\uber-ride-analytics-dashboard\versions\2


Date      Time    Booking ID   Booking Status   Customer ID  \
0  23-03-2024  12:29:38  "CNR5884300"  No Driver Found  "CID1982111"   
1  29-11-2024  18:01:39  "CNR1326809"       Incomplete  "CID4604802"   
2  23-08-2024  08:56:10  "CNR8494506"        Completed  "CID9202816"   
3  21-10-2024  17:17:25  "CNR8906825"        Completed  "CID2610914"   
4  16-09-2024  22:08:00  "CNR1950162"        Completed  "CID9933542"   

    Vehicle Type      Pickup Location      Drop Location  Avg VTAT  Avg CTAT  \
0          eBike          Palam Vihar            Jhilmil       NaN       NaN   
1       Go Sedan        Shastri Nagar  Gurgaon Sector 56       4.9      14.0   
2           Auto              Khandsa      Malviya Nagar      13.4      25.8   
3  Premier Sedan  Central Secretariat           Inderlok      13.1      28.5   
4           Bike     Ghitorni Village        Khan Market       5.3      19.6   

   ...  Reason for cancelling by Customer Cancelled Rides by Driver  \
0  ...                                NaN                       NaN   
1  ...                                NaN                       NaN   
2  ...                                NaN                       NaN   
3  ...                                NaN                       NaN   
4  ...                                NaN                       NaN   

   Driver Cancellation Reason Incomplete Rides  Incomplete Rides Reason  \
0                         NaN              NaN                      NaN   
1                         NaN              1.0        Vehicle Breakdown   
2                         NaN              NaN                      NaN   
3                         NaN              NaN                      NaN   
4                         NaN              NaN                      NaN   

  Booking Value  Ride Distance  Driver Ratings  Customer Rating  \
0           NaN            NaN             NaN              NaN   
1         237.0           5.73             NaN              NaN   
2         627.0          13.58             4.9              4.9   
3         416.0          34.02             4.6              5.0   
4         737.0          48.21             4.1              4.3   

   Payment Method  
0             NaN  
1             UPI  
2      Debit Card  
3             UPI  
4             UPI  

[5 rows x 21 columns]